/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-10 02:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chartjs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<!-- Required meta tags -->\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<title>Plus Admin</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/join/chartjs.css\" />\n");
      out.write("<!-- End layout styles -->\n");
      out.write("<style>\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container-scroller\">\n");
      out.write("		<!-- partial:partials/_sidebar.html -->\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\n");
      out.write("			<ul class=\"nav\">\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\"><a\n");
      out.write("					href=\"UpdatePage.do\" class=\"nav-link flex-column\">\n");
      out.write("						<div class=\"nav-profile-image\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\n");
      out.write("							<!--change to offline or busy as needed-->\n");
      out.write("						</div>\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("						</div>\n");
      out.write("				</a></li>\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\n");
      out.write("					href=\"MainPage.do\"> <img class=\"sidebar-brand-logo\"\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\n");
      out.write("						alt=\"\" />\n");
      out.write("						<div class=\"small font-weight-light pt-1\">fitness responsive\n");
      out.write("							web design</div>\n");
      out.write("				</a>\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\n");
      out.write("						</MENU>\n");
      out.write("				</span></li>\n");
      out.write("				<!--*** side nar > nav >  사용자 Menu start ***-->\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\"\n");
      out.write("					href=\"MainPage.do\"> <i\n");
      out.write("						class=\"mdi mdi-compass-outline menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\"\n");
      out.write("					href=\"ComparePage.do\"> <i class=\"mdi mdi-chart-bar menu-icon\"></i>\n");
      out.write("						<span class=\"menu-title\">나의운동비교</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\"\n");
      out.write("					href=\"InputPage.do\"> <i class=\"mdi mdi-check-circle menu-icon\"></i>\n");
      out.write("						<span class=\"menu-title\">나의운동입력</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\"\n");
      out.write("					href=\"ReservePage.do\"> <i\n");
      out.write("						class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\n");
      out.write("				</a></li>\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("\n");
      out.write("		<!-- partial -->\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\n");
      out.write("			<!-- partial:partials/_settings-panel.html -->\n");
      out.write("			<div id=\"settings-trigger\">\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\n");
      out.write("			</div>\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\n");
      out.write("					Default\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\n");
      out.write("					Dark\n");
      out.write("				</div>\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\n");
      out.write("					<div class=\"tiles default primary\"></div>\n");
      out.write("					<div class=\"tiles success\"></div>\n");
      out.write("					<div class=\"tiles warning\"></div>\n");
      out.write("					<div class=\"tiles danger\"></div>\n");
      out.write("					<div class=\"tiles info\"></div>\n");
      out.write("					<div class=\"tiles dark\"></div>\n");
      out.write("					<div class=\"tiles light\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- partial -->\n");
      out.write("			<nav\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\n");
      out.write("					</button>\n");
      out.write("					<div\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"MainPage.do\"><img\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\n");
      out.write("\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("								<div class=\"nav-profile-text\">MYPAGE</div>\n");
      out.write("						</a>\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\n");
      out.write("								aria-labelledby=\"profileDropdown\">\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\n");
      out.write("								</a>\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\n");
      out.write("								</a>\n");
      out.write("\n");
      out.write("								<!-- 변경부분 -->\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\n");
      out.write("								</a>\n");
      out.write("								<!-- 변경부분 -->\n");
      out.write("\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\n");
      out.write("								</a>\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\n");
      out.write("							class=\"nav-link\" href=\"MainPage.do\"> <i\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\n");
      out.write("						</a></li>\n");
      out.write("					</ul>\n");
      out.write("					<button\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("\n");
      out.write("			<!-- partial -->\n");
      out.write("			<div class=\"main-panel\">\n");
      out.write("				<div class=\"content-wrapper\">\n");
      out.write("					<!--  1행 시작 -->\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<!--  1행 시작 -->\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<!-- 1행 1열 -->\n");
      out.write("							<div class=\"col-lg-8 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<div class=\"row\">\n");
      out.write("											<!-- 왼쪽에 차트 배치 -->\n");
      out.write("											<div class=\"col-md-7\">\n");
      out.write("												<h4 class=\"card-title\">\n");
      out.write("													<strong class=\"chaname\">표준데이터 비교</strong>\n");
      out.write("												</h4>\n");
      out.write("												<canvas id=\"barChart\"></canvas>\n");
      out.write("											</div>\n");
      out.write("											<!-- 오른쪽에 표 배치 -->\n");
      out.write("											<div class=\"col-md-4 d-flex flex-column\">\n");
      out.write("												<table class=\"table\">\n");
      out.write("													<thead>\n");
      out.write("														<tr>\n");
      out.write("															<th scope=\"col\"><strong class=\"chaname\">개인\n");
      out.write("																	데이터</strong></th>\n");
      out.write("															<th scope=\"col\"><strong class=\"chaname\">표준\n");
      out.write("																	데이터</strong></th>\n");
      out.write("														</tr>\n");
      out.write("													</thead>\n");
      out.write("													<tbody>\n");
      out.write("														<tr>\n");
      out.write("															<td id=\"mem_height\"></td>\n");
      out.write("															<td id=\"std_height\"></td>\n");
      out.write("														</tr>\n");
      out.write("														<tr>\n");
      out.write("															<td id=\"mem_weight\"></td>\n");
      out.write("															<td id=\"std_weight\"></td>\n");
      out.write("														</tr>\n");
      out.write("														<tr>\n");
      out.write("															<td id=\"mem_bmi\"></td>\n");
      out.write("															<td id=\"std_bmi\"></td>\n");
      out.write("														</tr>\n");
      out.write("														<tr>\n");
      out.write("															<td id=\"mem_muscle\"></td>\n");
      out.write("															<td id=\"std_muscle\"></td>\n");
      out.write("														</tr>\n");
      out.write("														<tr>\n");
      out.write("															<td id=\"mem_fat_per\"></td>\n");
      out.write("															<td id=\"std_fat_per\"></td>\n");
      out.write("														</tr>\n");
      out.write("													</tbody>\n");
      out.write("												</table>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- 1행 2열 -->\n");
      out.write("							<div class=\"col-lg-4 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<h4 class=\"card-title\">\n");
      out.write("											<strong class=\"chaname\">radar 차트로 비교</strong>\n");
      out.write("										</h4>\n");
      out.write("										<canvas id=\"radarChart\">\n");
      out.write("									</canvas>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<!-- 2행 1열 -->\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-lg-4 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\" id=\"diet\"\n");
      out.write("										style=\"width: 100%; height: 100%; object-fit: cover;\">\n");
      out.write("										<h2>Diet</h2>\n");
      out.write("										<a href=\"#\" id=\"dietLink\">\n");
      out.write("											<h4 class=\"card-title \" id=\"dietTitle\">Title</h4> <img src=\"\"\n");
      out.write("											alt=\"Diet Image\" id=\"dietImage\" class=\"charimg\"\n");
      out.write("											class=\"charimg img-fluid\"\n");
      out.write("											style=\"max-width: 100%; height: auto;\">\n");
      out.write("										</a> </a>\n");
      out.write("										<canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- 2행  2열 -->\n");
      out.write("							<div class=\"col-lg-4 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\" id=\"news\"\n");
      out.write("										style=\"width: 100%; height: 100%; object-fit: cover;\">\n");
      out.write("										<h2>News</h2>\n");
      out.write("										<a href=\"#\" id=\"newsLink\">\n");
      out.write("											<h4 class=\"card-title \" id=\"newsTitle\">Title</h4> <img src=\"\"\n");
      out.write("											alt=\"News Image\" id=\"newsImage\" class=\"charimg img-fluid\"\n");
      out.write("											style=\"max-width: 100%; height: auto;\">\n");
      out.write("										</a> </a>\n");
      out.write("										<canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<!-- 2행 3열 -->\n");
      out.write("							<div class=\"col-lg-4 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body \" id=\"routine\"\n");
      out.write("										style=\"width: 100%; height: 100%; object-fit: cover;\">\n");
      out.write("										<h2>Routine</h2>\n");
      out.write("										<a href=\"#\" id=\"routineLink\">\n");
      out.write("											<h4 class=\"card-title\" id=\"routineTitle\">Title</h4> <img\n");
      out.write("											src=\"\" alt=\"Routine Image\" id=\"routineImage\"\n");
      out.write("											class=\"charimg img-fluid\"\n");
      out.write("											style=\"max-width: 100%; height: auto;\">\n");
      out.write("										</a>\n");
      out.write("										<canvas id=\"barChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- ** Footer Area START ** -->\n");
      out.write("					<footer class=\"footer\">\n");
      out.write("						<div\n");
      out.write("							class=\"d-sm-flex justify-content-center justify-content-sm-between\">\n");
      out.write("							<span\n");
      out.write("								class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\n");
      out.write("								© 2024 <a target=\"_blank\">Fitneeds</a>. All rights reserved.\n");
      out.write("							</span> <span\n");
      out.write("								class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">\n");
      out.write("								Fitneeds team & smhrd <i class=\"mdi mdi-heart text-danger\"></i>\n");
      out.write("							</span>\n");
      out.write("						</div>\n");
      out.write("					</footer>\n");
      out.write("					<!-- partial -->\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- container-scroller -->\n");
      out.write("		<!-- plugins:js -->\n");
      out.write("		<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\n");
      out.write("		<!-- endinject -->\n");
      out.write("		<!-- Plugin js for this page -->\n");
      out.write("		<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\n");
      out.write("		<!-- End plugin js for this page -->\n");
      out.write("		<!-- inject:js -->\n");
      out.write("		<script src=\"assets/js/off-canvas.js\"></script>\n");
      out.write("		<script src=\"assets/js/hoverable-collapse.js\"></script>\n");
      out.write("		<script src=\"assets/js/misc.js\"></script>\n");
      out.write("		<script src=\"assets/js/settings.js\"></script>\n");
      out.write("		<script src=\"assets/js/todolist.js\"></script>\n");
      out.write("		<!-- endinject -->\n");
      out.write("		<!-- Custom js for this page -->\n");
      out.write("		<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("		<script src=\"assets/js/chart.js\"></script>\n");
      out.write("		<!-- End custom js for this page -->\n");
      out.write("		<!-- flask에서 url받아오기-->\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("      // diet 정보 요청\n");
      out.write("      fetch('http://127.0.0.1:5000/diet')\n");
      out.write("        .then(response => response.json())\n");
      out.write("        .then(data => {\n");
      out.write("          console.log(data)\n");
      out.write("          document.getElementById('dietLink').href = data.url;\n");
      out.write("          document.getElementById('dietImage').src = data.thumb_url;\n");
      out.write("          document.getElementById('dietTitle').textContent = data.title;\n");
      out.write("        });\n");
      out.write("\n");
      out.write("      // news 정보 요청\n");
      out.write("      fetch('http://127.0.0.1:5000/news')\n");
      out.write("        .then(response => response.json())\n");
      out.write("        .then(data => {\n");
      out.write("          console.log(data)\n");
      out.write("          document.getElementById('newsLink').href = data.url;\n");
      out.write("          document.getElementById('newsImage').src = data.thumb_url;\n");
      out.write("          document.getElementById('newsTitle').textContent = data.title;\n");
      out.write("        });\n");
      out.write("\n");
      out.write("      // routine 정보 요청\n");
      out.write("      fetch('http://127.0.0.1:5000/routine')\n");
      out.write("        .then(response => response.json())\n");
      out.write("        .then(data => {\n");
      out.write("          console.log(data)\n");
      out.write("          document.getElementById('routineLink').href = data.url;\n");
      out.write("          document.getElementById('routineImage').src = data.thumb_url;\n");
      out.write("          document.getElementById('routineTitle').textContent = data.title;\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
