/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-10 02:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/index.global.min.js'></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.11/locales-all.min.js'></script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js\"></script>\n");
      out.write("\n");
      out.write("<title>Plus Admin</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendors/mdi/css/materialdesignicons.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendors/flag-icon-css/css/flag-icon.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/css/vendor.bundle.base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/style.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/indexplus.css\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/calendar.css\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("  .fc-myCustomButton-button {\n");
      out.write("    width: 80px;\n");
      out.write("    height: 40px;\n");
      out.write("    font-size : 0.5em;\n");
      out.write("  }\n");
      out.write("  .fc-myPlusButton-button {\n");
      out.write("    /* 버튼의 크기 조절 */\n");
      out.write("    width: 80px;\n");
      out.write("    height: 40px;\n");
      out.write("    font-size : 0.5em;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container-scroller\">\n");
      out.write("		<!-- partial:partials/_sidebar.html -->\n");
      out.write("		<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\n");
      out.write("			<ul class=\"nav\">\n");
      out.write("				<li class=\"nav-item nav-profile border-bottom\"><a href=\"#\"\n");
      out.write("					class=\"nav-link flex-column\">\n");
      out.write("						<div class=\"nav-profile-image\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"profile\" />\n");
      out.write("							<!--change to offline or busy as needed-->\n");
      out.write("						</div>\n");
      out.write("						<div class=\"nav-profile-text d-flex ms-0 mb-3 flex-column\">\n");
      out.write("							<span class=\"font-weight-semibold mb-1 mt-2 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("							<span class=\"text-secondary icon-sm text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("						</div>\n");
      out.write("				</a></li>\n");
      out.write("				<li class=\"nav-item pt-3\"><a class=\"nav-link d-block\"\n");
      out.write("					href=\"MainPage.do\"> <img class=\"sidebar-brand-logo\"\n");
      out.write("						src=\"assets/images/logo.png\" alt=\"\" /> <img\n");
      out.write("						class=\"sidebar-brand-logomini\" src=\"assets/images/logo-mini.png\"\n");
      out.write("						alt=\"\" />\n");
      out.write("						<div class=\"small font-weight-light pt-1\">fitness responsive\n");
      out.write("							web design</div>\n");
      out.write("				</a>\n");
      out.write("					<form class=\"d-flex align-items-center\" action=\"#\"></form></li>\n");
      out.write("				<li class=\"pt-2 pb-1\"><span class=\"nav-item-head\">MENU\n");
      out.write("						</MENU>\n");
      out.write("				</span></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"MainPage.do\">\n");
      out.write("						<i class=\"mdi mdi-compass-outline menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동정보</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"ComparePage.do\">\n");
      out.write("						<i class=\"mdi mdi-chart-bar menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동비교</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"InputPage.do\">\n");
      out.write("						<i class=\"mdi mdi-check-circle menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동입력</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item nav-effect\"><a class=\"nav-link\" href=\"ReservePage.do\">\n");
      out.write("						<i class=\"mdi mdi-comment-account-outline menu-icon\"></i> <span\n");
      out.write("						class=\"menu-title\">나의운동예약</span>\n");
      out.write("				</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("\n");
      out.write("		<div class=\"container-fluid page-body-wrapper\">\n");
      out.write("			<div id=\"settings-trigger\">\n");
      out.write("				<i class=\"mdi mdi-settings\"></i>\n");
      out.write("			</div>\n");
      out.write("			<div id=\"theme-settings\" class=\"settings-panel\">\n");
      out.write("				<i class=\"settings-close mdi mdi-close\"></i>\n");
      out.write("				<p class=\"settings-heading\">SIDEBAR SKINS</p>\n");
      out.write("				<div class=\"sidebar-bg-options selected\" id=\"sidebar-default-theme\">\n");
      out.write("					<div class=\"img-ss rounded-circle bg-light border me-3\"></div>\n");
      out.write("					Default\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sidebar-bg-options\" id=\"sidebar-dark-theme\">\n");
      out.write("					<div class=\"img-ss rounded-circle bg-dark border me-3\"></div>\n");
      out.write("					Dark\n");
      out.write("				</div>\n");
      out.write("				<p class=\"settings-heading mt-2\">HEADER SKINS</p>\n");
      out.write("				<div class=\"color-tiles mx-0 px-4\">\n");
      out.write("					<div class=\"tiles default primary\"></div>\n");
      out.write("					<div class=\"tiles success\"></div>\n");
      out.write("					<div class=\"tiles warning\"></div>\n");
      out.write("					<div class=\"tiles danger\"></div>\n");
      out.write("					<div class=\"tiles info\"></div>\n");
      out.write("					<div class=\"tiles dark\"></div>\n");
      out.write("					<div class=\"tiles light\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<nav\n");
      out.write("				class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\n");
      out.write("				<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\n");
      out.write("					<button class=\"navbar-toggler navbar-toggler align-self-center\"\n");
      out.write("						type=\"button\" data-toggle=\"minimize\">\n");
      out.write("						<span class=\"mdi mdi-chevron-double-left\"></span>\n");
      out.write("					</button>\n");
      out.write("					<div\n");
      out.write("						class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\n");
      out.write("						<a class=\"navbar-brand brand-logo-mini\" href=\"MainPage.do\"><img\n");
      out.write("							src=\"assets/images/logo-mini.png\" alt=\"logo\" /></a>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<ul class=\"navbar-nav navbar-nav-right\">\n");
      out.write("\n");
      out.write("						<li class=\"nav-item nav-profile dropdown d-none d-md-block\">\n");
      out.write("							<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\"\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							<div class=\"nav-profile-text\">MYPAGE</div>\n");
      out.write("						</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("							<div class=\"dropdown-menu center navbar-dropdown\"\n");
      out.write("								aria-labelledby=\"profileDropdown\">\n");
      out.write("								<a class=\"dropdown-item\" href=\"UpdatePage.do\"> <i\n");
      out.write("									class=\"mdi mdi-account-circle me-3\"></i> 회원정보수정\n");
      out.write("								</a>\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"InputPage.do\"> <i\n");
      out.write("									class=\"mdi mdi-check-circle me-3\"></i> 나의운동입력\n");
      out.write("								</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("				\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"WeightPage.do\"> <i\n");
      out.write("									class=\"mdi mdi-poll-box me-3\"></i> 나의체중입력\n");
      out.write("								</a>\n");
      out.write("		\n");
      out.write("\n");
      out.write("\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("								<a class=\"dropdown-item\" href=\"Logout.do\"> <i\n");
      out.write("									class=\"mdi mdi-logout-variant me-3\"></i> 로그아웃\n");
      out.write("								</a>\n");
      out.write("								<div class=\"dropdown-divider\"></div>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<li class=\"nav-item nav-logout d-none d-lg-block\"><a\n");
      out.write("							class=\"nav-link\" href=\"MainPage.do\"> <i\n");
      out.write("								class=\"mdi mdi-home-circle\"></i>\n");
      out.write("						</a></li>\n");
      out.write("					</ul>\n");
      out.write("					<button\n");
      out.write("						class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\n");
      out.write("						type=\"button\" data-toggle=\"offcanvas\">\n");
      out.write("						<span class=\"mdi mdi-menu\"></span>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("\n");
      out.write("			<div class=\"main-panel\">\n");
      out.write("				<div class=\"content-wrapper\">\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"data-input\">\n");
      out.write("						<input type=\"text\" class=\"btn btn-outline-dark bg-white\"\n");
      out.write("							name=\"start_date\" id=\"exampleInputDate\" placeholder=\"조회시작일\" /> <input\n");
      out.write("							type=\"text\" class=\"btn btn-outline-dark bg-white\" name=\"end_date\"\n");
      out.write("							id=\"exampleInputDate1\" placeholder=\"조회종료일\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("						<button type=\"submit\" id=\"date_check\"\n");
      out.write("							class=\"btn btn-dark me-2 btn-bg\">적용</button>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"row\">\n");
      out.write("\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-xl-8 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card card-calender\"\n");
      out.write("									style=\"background-image: url('assets/images/intro/flower.gif'); background-size: cover;\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<div class=\"row pt-4 d-flex\">\n");
      out.write("											<div class=\"col-sm-6 text-sm-right pt-3 pt-sm-0 \">\n");
      out.write("\n");
      out.write("												<h6 class=\"text\" style=\"background-color: #ffffff; color: #926168; display: inline-block;\" >Welcome FitNeeds</h6>\n");
      out.write("												<h1 class=\"text-white m-0 text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mem_nick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님,</h1>\n");
      out.write("												<h3 class=\"text-white m-0 text-center\" id=\"change_sentence\" style=\"background-color: #926168; color: #FFFFFF;\"></h3>\n");
      out.write("									\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-xl-4 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<div class=\"d-flex justify-content-between align-items-start\">\n");
      out.write("											<div class=\"card-body\">\n");
      out.write("												<p class=\"m-0 survey-head\"><strong class=\"chaname\">출석률</strong></p>\n");
      out.write("												<canvas id=\"countDateChart\"></canvas>\n");
      out.write("												<p id=\"attendanceRate\" class =\"indexDC\"></p>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<h4 class=\"card-title\">신체 데이터 변화량</h4>\n");
      out.write("										<canvas id=\"lineChart\"></canvas>\n");
      out.write("										<p id=\"averageBMI\" class=\"indexfont\"></p>\n");
      out.write("										<p id=\"averageMuscle\" class=\"indexfont\"></p>\n");
      out.write("										<p id=\"averageFatPercentage\" class=\"indexfont\"></p>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<h4 class=\"card-title\">소모 칼로리 변화량</h4>\n");
      out.write("										<canvas id=\"lineChartCalories\"></canvas>\n");
      out.write("										<p id=\"maxCalories\" class=\"indexfont\"></p>\n");
      out.write("										<p id=\"averageCalories\" class=\"indexfont\"></p>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-xl-6 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<div id='calendar-container'>\n");
      out.write("											<div id='calendar'></div>\n");
      out.write("										</div>\n");
      out.write("										<!-- 수정 모달 -->\n");
      out.write("										<div class=\"modal fade\" id=\"editModal\" tabindex=\"-1\"\n");
      out.write("											aria-labelledby=\"editModalLabel\" aria-hidden=\"true\">\n");
      out.write("											<div class=\"modal-dialog\">\n");
      out.write("												<div class=\"modal-content\">\n");
      out.write("													<div class=\"modal-header\">\n");
      out.write("														<h5 class=\"modal-title\" id=\"editModalLabel\">일정 수정하기</h5>\n");
      out.write("														<button type=\"button\" class=\"btn-close\"\n");
      out.write("															data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"modal-body\">\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"editTitle\" class=\"form-label\">일정이름</label> <input\n");
      out.write("																type=\"text\" class=\"form-control\" id=\"editTitle\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"editStart\" class=\"form-label\">시작시간</label> <input\n");
      out.write("																type=\"datetime-local\" class=\"form-control\"\n");
      out.write("																id=\"editStart\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"editEnd\" class=\"form-label\">종료시간</label> <input\n");
      out.write("																type=\"datetime-local\" class=\"form-control\" id=\"editEnd\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"editColor\" class=\"form-label\">배경색상</label> <select\n");
      out.write("																class=\"form-select\" id=\"editColor\">\n");
      out.write("																<option value=\"red\">빨강색</option>\n");
      out.write("																<option value=\"orange\">주황색</option>\n");
      out.write("																<option value=\"yellow\">노랑색</option>\n");
      out.write("																<option value=\"green\">초록색</option>\n");
      out.write("																<option value=\"blue\">파랑색</option>\n");
      out.write("																<option value=\"indigo\">남색</option>\n");
      out.write("																<option value=\"purple\">보라색</option>\n");
      out.write("															</select>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"modal-footer\">\n");
      out.write("														<button type=\"button\" class=\"btn btn-danger\"\n");
      out.write("															id=\"deleteEvent\">삭제</button>\n");
      out.write("														<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("															id=\"saveEditChanges\">저장</button>\n");
      out.write("														<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("															data-bs-dismiss=\"modal\">취소</button>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("										<!-- 추가 모달 -->\n");
      out.write("										<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\n");
      out.write("											aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("											<div class=\"modal-dialog\">\n");
      out.write("												<div class=\"modal-content\">\n");
      out.write("													<div class=\"modal-header\">\n");
      out.write("														<h5 class=\"modal-title\" id=\"exampleModalLabel\">일정\n");
      out.write("															추가하기</h5>\n");
      out.write("														<button type=\"button\" class=\"btn-close\"\n");
      out.write("															data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"modal-body\">\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"title\" class=\"form-label\">일정이름</label> <input\n");
      out.write("																type=\"text\" class=\"form-control\" id=\"title\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"start\" class=\"form-label\">시작시간</label> <input\n");
      out.write("																type=\"datetime-local\" class=\"form-control\" id=\"start\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"end\" class=\"form-label\">종료시간</label> <input\n");
      out.write("																type=\"datetime-local\" class=\"form-control\" id=\"end\">\n");
      out.write("														</div>\n");
      out.write("														<div class=\"mb-3\">\n");
      out.write("															<label for=\"color\" class=\"form-label\">배경색상</label> <select\n");
      out.write("																class=\"form-select\" id=\"color\">\n");
      out.write("																<option value=\"red\">빨강색</option>\n");
      out.write("																<option value=\"orange\">주황색</option>\n");
      out.write("																<option value=\"yellow\">노랑색</option>\n");
      out.write("																<option value=\"green\">초록색</option>\n");
      out.write("																<option value=\"blue\">파랑색</option>\n");
      out.write("																<option value=\"indigo\">남색</option>\n");
      out.write("																<option value=\"purple\">보라색</option>\n");
      out.write("															</select>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"modal-footer\">\n");
      out.write("														<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("															data-bs-dismiss=\"modal\">취소</button>\n");
      out.write("														<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("															id=\"saveChanges\">추가</button>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-xl-6 grid-margin stretch-card\">\n");
      out.write("								<div class=\"card\">\n");
      out.write("									<div class=\"card-body\">\n");
      out.write("										<h4 class=\"card-title\">운동비율</h4>\n");
      out.write("										<canvas id=\"pieChart\"></canvas>\n");
      out.write("										<div>\n");
      out.write("										<p id=\"aerobicCount\" class=\"indexfont\"></p>\n");
      out.write("										<p id=\"upperBodyCount\" class=\"indexfont\"></p>\n");
      out.write("										<p id=\"lowerBodyCount\" class=\"indexfont\"></p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<footer class=\"footer\">\n");
      out.write("					<div\n");
      out.write("						class=\"d-sm-flex justify-content-center justify-content-sm-between\">\n");
      out.write("						<span\n");
      out.write("							class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright\n");
      out.write("							© 2024 <a target=\"_blank\">Fitneeds</a>. All rights reserved.\n");
      out.write("						</span> <span\n");
      out.write("							class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">\n");
      out.write("							Fitneeds team & smhrd <i class=\"mdi mdi-heart text-danger\"></i>\n");
      out.write("						</span>\n");
      out.write("					</div>\n");
      out.write("				</footer>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- js -->\n");
      out.write("	<script src=\"assets/vendors/js/vendor.bundle.base.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"assets/vendors/chart.js/Chart.min.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"assets/js/off-canvas.js\"></script>\n");
      out.write("	<script src=\"assets/js/hoverable-collapse.js\"></script>\n");
      out.write("	<script src=\"assets/js/misc.js\"></script>\n");
      out.write("	<script src=\"assets/js/settings.js\"></script>\n");
      out.write("	<script src=\"assets/js/todolist.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/chart.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("	<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/change_sentence.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("	<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		$(function() {\n");
      out.write("			$(\"#exampleInputDate\").datepicker({\n");
      out.write("				dateFormat : \"yy-mm-dd\"\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		$(function() {\n");
      out.write("			$(\"#exampleInputDate1\").datepicker({\n");
      out.write("				dateFormat : \"yy-mm-dd\"\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("<script>\n");
      out.write("		var calendar;\n");
      out.write("		var clickedEvent; // 클릭한 이벤트 정보를 저장하기 위한 전역 변수\n");
      out.write("		(function() {\n");
      out.write("			$(function() {\n");
      out.write("				// calendar element 취득\n");
      out.write("				var calendarEl = $('#calendar')[0];\n");
      out.write("				// full-calendar 생성하기\n");
      out.write("				var calendar = new FullCalendar.Calendar(\n");
      out.write("						calendarEl,\n");
      out.write("						{\n");
      out.write("							height : '700px', // calendar 높이 설정\n");
      out.write("							expandRows : true, // 화면에 맞게 높이 재설정\n");
      out.write("							slotMinTime : '08:00', // Day 캘린더에서 시작 시간\n");
      out.write("							slotMaxTime : '20:00', // Day 캘린더에서 종료 시간\n");
      out.write("							customButtons : {\n");
      out.write("								myCustomButton : {\n");
      out.write("									text : \"운동기록\",\n");
      out.write("									click : function() {\n");
      out.write("										window.location.href = \"http://localhost:8080/GitProject/fitmyhealth.do\";\n");
      out.write("									}\n");
      out.write("								},\n");
      out.write("\n");
      out.write("								myPlusButton : {\n");
      out.write("									text : \"일정추가\",\n");
      out.write("									click : function() {\n");
      out.write("										//부트스트랩 모달 열기\n");
      out.write("										$(\"#exampleModal\").modal(\"show\");\n");
      out.write("									}\n");
      out.write("								}\n");
      out.write("							},\n");
      out.write("							// 해더에 표시할 툴바\n");
      out.write("							headerToolbar : {\n");
      out.write("								left : 'prev,today,myPlusButton,myCustomButton',\n");
      out.write("								center : 'title',\n");
      out.write("								right : 'dayGridMonth,timeGridWeek,timeGridDay,listWeek,next'\n");
      out.write("							},\n");
      out.write("							initialView : 'dayGridMonth', // 초기 로드 될때 보이는 캘린더 화면(기본 설정: 달)\n");
      out.write("							// initialDate: '2024-04-02', // 초기 날짜 설정 (설정하지 않으면 오늘 날짜가 보인다.)\n");
      out.write("							navLinks : true, // 날짜를 선택하면 Day 캘린더나 Week 캘린더로 링크\n");
      out.write("							editable : true, // 수정 가능?\n");
      out.write("							selectable : true, // 달력 일자 드래그 설정가능\n");
      out.write("							nowIndicator : true, // 현재 시간 마크\n");
      out.write("							dayMaxEvents : true, // 이벤트가 오버되면 높이 제한 (+ 몇 개식으로 표현)\n");
      out.write("							locale : 'ko', // 한국어 설정\n");
      out.write("							eventAdd : function(obj) { // 이벤트가 추가되면 발생하는 이벤트\n");
      out.write("							},\n");
      out.write("							eventChange : function(obj) { // 이벤트가 수정되면 발생하는 이벤트\n");
      out.write("							},\n");
      out.write("							eventRemove : function(obj) { // 이벤트가 삭제되면 발생하는 이벤트\n");
      out.write("							},\n");
      out.write("							// 이벤트클릭을 이용한 데이터 수정\n");
      out.write("							eventClick : function(info) {\n");
      out.write("								// 클릭한 이벤트의 정보 가져오기\n");
      out.write("								clickedEvent = info.event;\n");
      out.write("								// 모달 폼에 이벤트 정보 채우기\n");
      out.write("								$(\"#editTitle\").val(clickedEvent.title);\n");
      out.write("								$(\"#editStart\").val(clickedEvent.startStr);\n");
      out.write("								$(\"#editEnd\").val(clickedEvent.endStr);\n");
      out.write("								$(\"#editColor\").val(\n");
      out.write("										clickedEvent.backgroundColor);\n");
      out.write("								// 수정 모달 열기\n");
      out.write("								$(\"#editModal\").modal(\"show\");\n");
      out.write("							},\n");
      out.write("							select : function(arg) { // 캘린더에서 드래그로 이벤트를 생성할 수 있다.\n");
      out.write("								var title = prompt('Event Title:');\n");
      out.write("								if (title) {\n");
      out.write("									calendar.addEvent({\n");
      out.write("										title : title,\n");
      out.write("										start : arg.start,\n");
      out.write("										end : arg.end,\n");
      out.write("										allDay : arg.allDay\n");
      out.write("									})\n");
      out.write("								}\n");
      out.write("								calendar.unselect()\n");
      out.write("							},\n");
      out.write("\n");
      out.write("						});\n");
      out.write("				// 캘린더 랜더링\n");
      out.write("				calendar.render();\n");
      out.write("\n");
      out.write("				// 문서가 로드될 때 자동으로 이벤트 불러오기\n");
      out.write("				fetchAndAddEvents();\n");
      out.write("\n");
      out.write("				// DB에 저장된 일정 가져오기\n");
      out.write("				function fetchAndAddEvents() {\n");
      out.write("					$.ajax({\n");
      out.write("						url : 'FetchCalendarEvent.do',\n");
      out.write("						method : 'POST',\n");
      out.write("						success : function(res) {\n");
      out.write("							// 받아온 이벤트들을 events 배열에 추가\n");
      out.write("							res.forEach(function(event) {\n");
      out.write("								calendar.addEvent(event);\n");
      out.write("							});\n");
      out.write("						},\n");
      out.write("						error : function() {\n");
      out.write("							console.log(\"이벤트 불러오기 실패\");\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				}\n");
      out.write("\n");
      out.write("				// 모달창 이벤트 // 일정 추가해서 화면에 띄워주기!\n");
      out.write("				$(\"#saveChanges\").on(\n");
      out.write("						\"click\",\n");
      out.write("						function() {\n");
      out.write("							var eventData = {\n");
      out.write("								title : $(\"#title\").val(),\n");
      out.write("								start : $(\"#start\").val(),\n");
      out.write("								end : $(\"#end\").val(),\n");
      out.write("								color : $(\"#color\").val(),\n");
      out.write("							};\n");
      out.write("							//빈값입력시 오류\n");
      out.write("							if (eventData.title == \"\" || eventData.start == \"\"\n");
      out.write("									|| eventData.end == \"\") {\n");
      out.write("								alert(\"입력하지 않은 값이 있습니다.\");\n");
      out.write("\n");
      out.write("								//끝나는 날짜가 시작하는 날짜보다 값이 크면 안됨\n");
      out.write("							} else if ($(\"#start\").val() > $(\"#end\").val()) {\n");
      out.write("								alert(\"시간을 잘못입력 하셨습니다.\");\n");
      out.write("							} else {\n");
      out.write("								// 이벤트 추가\n");
      out.write("								$(\"#exampleModal\").modal(\"hide\");\n");
      out.write("								$(\"#title\").val(\"\");\n");
      out.write("								$(\"#start\").val(\"\");\n");
      out.write("								$(\"#end\").val(\"\");\n");
      out.write("								$(\"#color\").val(\"\");\n");
      out.write("								// db에 저장\n");
      out.write("								$.ajax({\n");
      out.write("									url : 'CalendarSave.do',\n");
      out.write("									method : 'POST',\n");
      out.write("									data : eventData,\n");
      out.write("									success : function(response) {\n");
      out.write("										console.log(\"성공\");\n");
      out.write("										calendar.addEvent(eventData);\n");
      out.write("									},\n");
      out.write("									error : function(xhr, status, error) {\n");
      out.write("									}\n");
      out.write("								});\n");
      out.write("\n");
      out.write("							}\n");
      out.write("						});\n");
      out.write("\n");
      out.write("				// 수정 모달 저장 버튼 클릭 시 수정된 정보 전송\n");
      out.write("				$(\"#saveEditChanges\").on(\n");
      out.write("						\"click\",\n");
      out.write("						function() {\n");
      out.write("							var eventData = {\n");
      out.write("								title : $(\"#editTitle\").val(),\n");
      out.write("								start : $(\"#editStart\").val(),\n");
      out.write("								end : $(\"#editEnd\").val(),\n");
      out.write("								color : $(\"#editColor\").val(),\n");
      out.write("								cal_idx : clickedEvent.id, // clickedEvent 변수 사용\n");
      out.write("							};\n");
      out.write("\n");
      out.write("							$.ajax({\n");
      out.write("								url : \"CalendarUpdate.do\",\n");
      out.write("								method : 'POST',\n");
      out.write("								data : eventData,\n");
      out.write("								success : function(response) {\n");
      out.write("									clickedEvent.setProp('title',\n");
      out.write("											eventData.title);\n");
      out.write("									clickedEvent.setStart(eventData.start);\n");
      out.write("									clickedEvent.setEnd(eventData.end);\n");
      out.write("									clickedEvent.setProp('backgroundColor',\n");
      out.write("											eventData.color);\n");
      out.write("									calendar.refetchEvents();\n");
      out.write("									$(\"#editModal\").modal(\"hide\");\n");
      out.write("								},\n");
      out.write("								error : function(xhr, status, error) {\n");
      out.write("									console.error(\"이벤트 업데이트 실패:\", error);\n");
      out.write("								}\n");
      out.write("							});\n");
      out.write("						});\n");
      out.write("\n");
      out.write("				// 삭제 기능\n");
      out.write("				$(\"#deleteEvent\").on(\"click\", function() {\n");
      out.write("					// 선택한 이벤트의 시작 날짜와 종료 날짜 가져오기\n");
      out.write("					var eventData = {\n");
      out.write("						cal_idx : clickedEvent.id\n");
      out.write("					};\n");
      out.write("\n");
      out.write("					$.ajax({\n");
      out.write("						url : \"CalendarDelete.do\",\n");
      out.write("						method : 'POST',\n");
      out.write("						data : eventData,\n");
      out.write("						success : function(response) {\n");
      out.write("							clickedEvent.remove();\n");
      out.write("							$(\"#editModal\").modal(\"hide\");\n");
      out.write("						},\n");
      out.write("						error : function(xhr, status, error) {\n");
      out.write("							console.error(\"이벤트 삭제 실패:\", error);\n");
      out.write("						}\n");
      out.write("					});\n");
      out.write("				});\n");
      out.write("				// 스타일 적용\n");
      out.write("		        // myCustomButton 버튼의 스타일을 변경\n");
      out.write("		        $(\".fc-myCustomButton-button\").css(\"font-size\", \"0.9em\");\n");
      out.write("		        // myPlusButton 버튼의 스타일을 변경\n");
      out.write("		        $(\".fc-myPlusButton-button\").css(\"font-size\", \"0.9em\");\n");
      out.write("			});\n");
      out.write("		})();\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
