/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-10 02:23:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Insert title here</title>\n");
      out.write("    <link rel=\"stylesheet\"  href=\"assets/css/demo_1/intro.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/scrollify/1.0.19/jquery.scrollify.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!--메인 상단바 -->\n");
      out.write("    <header id=\"header\">\n");
      out.write("        <nav class=\"menu\">\n");
      out.write("            <ul>\n");
      out.write("                <li><img role=\"button\" src=\"assets/images/intro/rogo.png\" alt=\"FitNeeds\" class=\"headerfitImg\"></li>\n");
      out.write("                <li>\n");
      out.write("                	<a href=\"http://localhost:8080/GitProject/fitjoin.do\">\n");
      out.write("                		<img role=\"button\" src =\"assets/images/intro/introbtn3.png\" \n");
      out.write("                		class=\"headerImg\">\n");
      out.write("                	</a>\n");
      out.write("                	</li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("    </header>\n");
      out.write("    <!-- 페이지구분 -->\n");
      out.write("    <!--page1-->\n");
      out.write("    <div class=\"panel panel1 home active\" data-section-name=\"우리의 시작\">\n");
      out.write("        <div class=\"shape\">\n");
      out.write("            <div class=\"home1Img\">\n");
      out.write("                <img src=\"assets/images/intro/home1.png\" alt=\"대한민국 1등 건강관리 앱\">\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"hometest\">우리의 건강이야기 지금 시작합니다</h3>\n");
      out.write("            <div class=\"home\"></div>\n");
      out.write("            <div class=\"home2Img\">\n");
      out.write("                <img src=\"assets/images/intro/home2.png\" alt=\"우리의 마스코트\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--page2-->\n");
      out.write("    <div class=\"panel panel2\" data-section-name=\"대한민국 1등 건강관리 웹&앱\">\n");
      out.write("        <div class=\"shape\">\n");
      out.write("            <div class=\"panel21Img\">\n");
      out.write("                <img src=\"assets/images/intro/panel21.png\" alt=\"문구\">\n");
      out.write("            </div>\n");
      out.write("            <h3 class=\"panel2test\"></h3>\n");
      out.write("            <div class=\"home\"></div>\n");
      out.write("            <div class=\"panel22Img\">\n");
      out.write("                <img src=\"assets/images/intro/hell.png\" alt=\"자기관리 이미지\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--page3-->\n");
      out.write("    <div class=\"panel panel3\" data-section-name=\"FitNeeds 함께\">\n");
      out.write("        <div class=\"shape\">\n");
      out.write("            <div class=\"swiper-container\" style=\"width: 100%; height: 70%;\">\n");
      out.write("                <div class=\"swiper-wrapper\">\n");
      out.write("                    <div class=\"swiper-slide active\"><img src=\"assets/images/intro/s1.png\" alt=\"1번\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/intro/s2.png\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/intro/s3.png\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/intro/s4.png\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/intro/rogo.png\" alt=\"test\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-pagination\"></div> \n");
      out.write("                <div class=\"swiper-button-prev\"></div> \n");
      out.write("                <div class=\"swiper-button-next\"></div> \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("	<!--page4-->\n");
      out.write("    <div class=\"panel panel1\" data-section-name=\"FitNeeds 둘러보기\">\n");
      out.write("        <div class=\"shape\">\n");
      out.write("            <div class=\"swiper-container\" style=\"width: 100%; height: 70%;\">\n");
      out.write("                <div class=\"swiper-wrapper\">\n");
      out.write("                    <div class=\"swiper-slide active\"><img src=\"assets/images/banner/slide1.jpg\" alt=\"1번\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/banner/slide2.jpg\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/banner/slide3.jpg\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/banner/slide4.jpg\" alt=\"test\"></div>\n");
      out.write("                    <div class=\"swiper-slide\"><img src=\"assets/images/banner/slide5.jpg\" alt=\"test\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-pagination\"></div> \n");
      out.write("                <div class=\"swiper-button-prev\"></div> \n");
      out.write("                <div class=\"swiper-button-next\"></div> \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--page5-->\n");
      out.write("    <div class=\"panel panel4\" data-section-name=\"마치며\">\n");
      out.write("        <div class=\"shape\">\n");
      out.write("            <div class=\"panel41Img\">\n");
      out.write("                <img src=\"assets/images/intro/final.png\" alt=\"대한민국 1등 건강관리 앱\">\n");
      out.write("            </div>\n");
      out.write("            <h5 class=\"panel4test\">\n");
      out.write("                (주)FitNeeds<br>\n");
      out.write("                광주 광산구 월곡산정로 80 13층<br>\n");
      out.write("                <br>\n");
      out.write("                사업자번호 : 123-12-1231241243<br>\n");
      out.write("                통신판매업 : 광주 광산구 123<br>\n");
      out.write("                전자금융분쟁처리 TEL : 1234-1234 FAX :  02-123-1234<br>\n");
      out.write("                MAIL : kws1234@naver.com\n");
      out.write("            </h3>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/scrollify/1.0.19/jquery.scrollify.min.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/intro.js\"></script>\n");
      out.write("</html>>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
