/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-10 02:24:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.ibatis.reflection.SystemMetaObject;
import java.security.SecureRandom;
import java.net.URLEncoder;
import java.math.BigInteger;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/LG/Desktop/FitNeeds/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/GitProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ko.js\"></script>\n");
      out.write("\n");
      out.write("<title>ChariTeam - Free Nonprofit Website Template</title>\n");
      out.write("<meta content=\"\" name=\"keywords\">\n");
      out.write("<meta content=\"\" name=\"description\">\n");
      out.write("\n");
      out.write("<!-- Favicon -->\n");
      out.write("<link href=\"img/favicon.ico\" rel=\"icon\">\n");
      out.write("\n");
      out.write("<!-- Google Web Fonts -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Icon Font Stylesheet -->\n");
      out.write("<link\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/lib/join/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/css/demo_1/join/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/css/demo_1/join/style.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/demo_1/calendar.css\" />\n");
      out.write("<link href=\"assets/css/demo_1/signup/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/css/demo_1/signup/style.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/css/demo_1/signup/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	");

	String clientId = "gbLrG9lQfNuwCCfz4nge";//애플리케이션 클라이언트 아이디값";
	String redirectURI = URLEncoder.encode("http://localhost:8080/GitProject/fitcallback.do", "UTF-8");
	SecureRandom random = new SecureRandom();
	String state = new BigInteger(130, random).toString();
	String apiURL = "https://nid.naver.com/oauth2.0/authorize?response_type=code" + "&client_id=" + clientId
			+ "&redirect_uri=" + redirectURI + "&state=" + state;
	session.setAttribute("state", state);
	
      out.write("\n");
      out.write("	<!-- Carousel Start -->\n");
      out.write("	<div class=\"container-fluid p-0 mb-5\">\n");
      out.write("		<div id=\"header-carousel\" class=\"carousel slide\"\n");
      out.write("			data-bs-ride=\"carousel\">\n");
      out.write("			<div class=\"carousel-inner\">\n");
      out.write("				<!-- 로그인 START -->\n");
      out.write("				<div class=\"carousel-item active\" id=\"carousel-login\">\n");
      out.write("					<img class=\"w-100\" src=\"assets/images/join/carousel-bg.jpg\"\n");
      out.write("						alt=\"Image\">\n");
      out.write("					<div class=\"carousel-caption\">\n");
      out.write("						<div class=\"container\">\n");
      out.write("							<form class=\"join-form\" action=\"Login.do\" method=\"post\">\n");
      out.write("								<div class=\"row justify-content-center\">\n");
      out.write("									<div class=\"col-lg-7 pt-5\">\n");
      out.write("										<h1 class=\"display-4 text-white mb-3 animated slideInDown\">Login</h1>\n");
      out.write("										<p class=\"fs-5 text-white-50 mb-5 animated slideInDown\">Fitneeds\n");
      out.write("											로그인을 해볼까요 :)</p>\n");
      out.write("										<!-- 로그인 START -->\n");
      out.write("										<div class=\"row g-3\">\n");
      out.write("											<div class=\"col-12\">\n");
      out.write("												<div class=\"form-floating\">\n");
      out.write("													<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("														id=\"mem_id\" name=\"mem_id\" placeholder=\"Your Name\">\n");
      out.write("													<label>아이디</label>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("											<div class=\"col-12\">\n");
      out.write("												<div class=\"form-floating\">\n");
      out.write("													<input type=\"password\"\n");
      out.write("														class=\"form-control bg-light border-0\" id=\"mem_pw\"\n");
      out.write("														name=\"mem_pw\" placeholder=\"Your Email\"> <label>비밀번호</label>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<!-- 로그인input END -->\n");
      out.write("\n");
      out.write("\n");
      out.write("										<!-- naverButton -->\n");
      out.write("										<a href=\"");
      out.print(apiURL);
      out.write("\" class=\"btn animated slideInDown\"> <img\n");
      out.write("											height=\"50\"\n");
      out.write("											src=\"http://static.nid.naver.com/oauth/small_g_in.PNG\" /></a>\n");
      out.write("										<button type=\"submit\" id=\"login-form-submit\"\n");
      out.write("											class=\"btn btn-primary py-2 px-3 animated slideInDown\"\n");
      out.write("											href=\"#\">\n");
      out.write("											로그인\n");
      out.write("											<div\n");
      out.write("												class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("												<i class=\"fa fa-check\"></i>\n");
      out.write("											</div>\n");
      out.write("										</button>\n");
      out.write("							</form>\n");
      out.write("							<a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-next\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\" id=\"join_btn\"\n");
      out.write("								data-bs-slide=\"next\" disabled> 회원가입\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-right\"></i>\n");
      out.write("								</div>\n");
      out.write("							</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!--page1 start-->\n");
      out.write("		<div class=\"carousel-item second\" id=\"carousel-first\">\n");
      out.write("			<img class=\"w-100\" src=\"assets/images/join/carousel-bg.jpg\"\n");
      out.write("				alt=\"Image\">\n");
      out.write("			<div class=\"carousel-caption active\">\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-7 pt-5\">\n");
      out.write("							<h1 class=\"display-4 text-white mb-3 animated slideInDown\">Sign\n");
      out.write("								up</h1>\n");
      out.write("							<p class=\"fs-5 text-white-50 mb-5 animated slideInDown\">Fitneeds\n");
      out.write("								회원가입을 도와드릴게요 :)</p>\n");
      out.write("							<div>\n");
      out.write("								<div class=\"row g-3\">\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<form class=\"join-form\" action=\"Join.do\" method=\"post\"\n");
      out.write("											onsubmit=\"showSuccessAlert()\">\n");
      out.write("											<div class=\"form-floating\">\n");
      out.write("												<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("													id=\"mem_id\" name=\"mem_id\" placeholder=\"아이디를 입력해 주세요.\">\n");
      out.write("												<label>아이디</label>\n");
      out.write("											</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_pw\" name=\"mem_pw\" placeholder=\"Your Email\">\n");
      out.write("											<label for=\"email\">비밀번호</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_nick\" name=\"mem_nick\" placeholder=\"Your Email\">\n");
      out.write("											<label for=\"email\">닉네임</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-prev\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\"\n");
      out.write("								data-bs-slide=\"prev\">\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-left\"></i>\n");
      out.write("								</div> 로그인\n");
      out.write("							</a> \n");
      out.write("							<a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-next\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\" id=\"1st-next\"\n");
      out.write("								data-bs-slide=\"next\" disabled> Next Step\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-right\"></i>\n");
      out.write("								</div>\n");
      out.write("							</a>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<!-- page2 start -->\n");
      out.write("		<div class=\"carousel-item second\">\n");
      out.write("			<img class=\"w-100\" src=\"assets/images/join/carousel-bg.jpg\"\n");
      out.write("				alt=\"Image\">\n");
      out.write("			<div class=\"carousel-caption active\">\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-7 pt-5\">\n");
      out.write("							<h1 class=\"display-4 text-white mb-3 animated slideInDown\">총\n");
      out.write("								3단계로 구성되어 있어요!</h1>\n");
      out.write("							<p class=\"fs-5 text-white-50 mb-5 animated slideInDown\">회원가입에\n");
      out.write("								필요한 기본정보입력 해주세요.</p>\n");
      out.write("							<div>\n");
      out.write("\n");
      out.write("								<div class=\"row g-3\">\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_name\" placeholder=\"\" name=\"mem_name\" required\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <label for=\"name\">이름</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\" id=\"divBirthday\">\n");
      out.write("											<input type=\"text\"\n");
      out.write("												class=\"input form-control bg-light border-0\"\n");
      out.write("												id=\"exampleInputDate\" placeholder=\"생년월일\" maxlength=\"10\"\n");
      out.write("												name=\"mem_birthdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${birthyear}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("											<label for=\"text\">생년월일</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_addr\" placeholder=\"주소를 입력해 주세요\" name=\"mem_addr\"\n");
      out.write("												required> <label>주소</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_phone\" placeholder=\"핸드폰번호\" name=\"mem_phone\"\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <label for=\"text\">핸드폰번호</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"mem_email\" placeholder=\"이메일\" name=\"mem_email\"\n");
      out.write("												value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <label>이메일</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-prev\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\"\n");
      out.write("								data-bs-slide=\"prev\">\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-left\"></i>\n");
      out.write("								</div> Prev Step\n");
      out.write("							</a> <a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-next\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\" id=\"2nd-next\"\n");
      out.write("								data-bs-slide=\"next\"> Next Step\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-right\"></i>\n");
      out.write("								</div>\n");
      out.write("							</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- 3page start-->\n");
      out.write("		<div class=\"carousel-item third\">\n");
      out.write("			<img class=\"w-100\" src=\"assets/images/join/carousel-bg.jpg\"\n");
      out.write("				alt=\"Image\">\n");
      out.write("			<div class=\"carousel-caption\">\n");
      out.write("				<div class=\"container\">\n");
      out.write("					<div class=\"row justify-content-center\">\n");
      out.write("						<div class=\"col-lg-7 pt-5\">\n");
      out.write("							<h1 class=\"display-4 text-white mb-3 animated slideInDown\">마지막단계에요\n");
      out.write("								:)</h1>\n");
      out.write("							<p class=\"fs-5 text-white-50 mb-5 animated slideInDown\">내 정보를\n");
      out.write("								입력하시면 비교데이터를 볼 수 있어요!</p>\n");
      out.write("							<div>\n");
      out.write("								<div class=\"row g-3\">\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"height\" name=\"height\" placeholder=\"Your Name\"> <label>키</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"form-floating\">\n");
      out.write("											<input type=\"text\" class=\"form-control bg-light border-0\"\n");
      out.write("												id=\"weight\" placeholder=\"몸무게\" name=\"weight\"> <label>몸무게</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"col-12\">\n");
      out.write("										<div class=\"btn-group d-flex justify-content-around\">\n");
      out.write("											<input type=\"radio\" class=\"btn-check\" id=\"btnradio1\"\n");
      out.write("												value=\"M\" name=\"mem_gender\" checked> <label\n");
      out.write("												class=\"btn btn-outline-dark py-3\" for=\"btnradio1\">남성</label>\n");
      out.write("											<input type=\"radio\" class=\"btn-check\" id=\"btnradio2\"\n");
      out.write("												value=\"F\" name=\"mem_gender\"> <label\n");
      out.write("												class=\"btn btn-outline-dark py-3\" for=\"btnradio2\">여성</label>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<a\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown carousel-control-prev\"\n");
      out.write("								type=\"button\" data-bs-target=\"#header-carousel\"\n");
      out.write("								data-bs-slide=\"prev\">\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-arrow-left\"></i>\n");
      out.write("								</div> Prev Step\n");
      out.write("							</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("							<button type=\"submit\" id=\"login-form-submit\"\n");
      out.write("								class=\"btn btn-primary py-2 px-3 animated slideInDown\" href=\"#\">\n");
      out.write("								가입완료\n");
      out.write("								<div\n");
      out.write("									class=\"d-inline-flex btn-sm-square bg-white text-primary rounded-circle ms-2\">\n");
      out.write("									<i class=\"fa fa-check\"></i>\n");
      out.write("\n");
      out.write("								</div>\n");
      out.write("							</button>\n");
      out.write("							</form>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- page3 end -->\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Carousel End -->\n");
      out.write("	<!-- JavaScript Libraries -->\n");
      out.write("	<script src=\"assets/js/join/joinJs.js\"></script>\n");
      out.write("	<script src=\"assets/js/join/bootstrap.bundle.js\"></script>\n");
      out.write("	<script src=\"assets/js/join_success.js\"></script>\n");
      out.write("	<script src=\"assets/js/check_login.js\"></script>\n");
      out.write("	<script src=\"assets/js/login_fail.js\"></script>\n");
      out.write("	\n");
      out.write("		    <!-- calendar JS START  -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"assets/js/join/datepick.js\"></script>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		$(function() {\n");
      out.write("			$(\"#exampleInputDate\").datepicker({\n");
      out.write("				dateFormat : \"yy-mm-dd\",\n");
      out.write("				yearRange : \"-100:+0\",\n");
      out.write("				changeYear : true\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
